### ISSUE TITLE
no module named markdown

### ISSUE THREAD

**Issue by dragonsKnight5** [MycroftAI/selene-backend#215]
Hi,
when I try to run the pipenv run python3 bootstrap_mycroft_db.py I get a ModuleNotFoundEror:
No module named markdown

I've have the python 3 markdown module installed both in pip and the operating system

I don't know if this is contributing to the problem but I'm trying to install on a virtual centos 7
machine

I would include a log file but I can't find one for python

**Comment by gtole342** [comment]
Did you run `pipenv install` to install all the dependencies? pipenv is both the virtual environment and package manager so having the module installed by pip may not work for use with pipenv.

**Comment by chrisveilleux** [comment]
This is related to a versioning issue with dependencies related to Flask.  It has been fixed in PR #308
