### ISSUE TITLE
Please remove duplicate Warrington from English towns list

### ISSUE THREAD

**Issue by robertsawko** [MycroftAI/selene-backend#224]
Hello,

I have been having issues with pairing my first mycroft device. After reading some issues I realised that duplicate town names of your list cause this problem as described [here](https://github.com/MycroftAI/mycroft-core/issues/2179#issuecomment-507539943).

After changing to London, pairing worked fine. Please remove second Warrington entry and I will update my device with correct location.

Thanks. And thanks for the effort on this very exciting project.

**Comment by schniepp** [comment]
I had exactly the same issue with Williamsburg, VA. I tried registering multiple times, and it would not let me register. (It seemed like things were fine, and there was no helpful error message at all.) There were two "Williamsburg" in the list, and neither of them worked. When I gave the name of another town nearby, it worked as expected. This was extremely confusing and frustrating.

**Comment by bendyzx** [comment]
I am still seeing two entries for Warrington, England, United Kingdom
