### ISSUE TITLE
Add device form not working

### ISSUE THREAD

**Issue by amneher** [MycroftAI/selene-backend#239]
**Describe the bug**

## This is https://account.mycroft.ai/devices/add before clicking the little head in the top right.
![Screenshot_2020-12-18 Account(1)](https://user-images.githubusercontent.com/5522819/102580776-d5d1db80-40c4-11eb-98af-aa2b32b22126.png)

## This is https://account.mycroft.ai/devices/add after clicking the little head in the top right and making selections.
![Screenshot_2020-12-18 Account](https://user-images.githubusercontent.com/5522819/102580695-ac18b480-40c4-11eb-8ab8-ab54047d607f.png)

**To Reproduce**
1. Go to 'https://account.mycroft.ai/devices/add'
2. the form isn't loading unless I click on the account button.
3. I get the form after clicking the account button. Then, I select the appropriate settings, but the next button is still disabled.

**Expected behavior**
the 'next' button should be enabled once settings are selected.

**Environment (please complete the following information):**
 - Device type: lenovo t490
 - OS: ubuntu 20.04
 - Browser: Mozilla Firefox 84.0 & Google Chrome 87.0.4280.88 
 
Tried using firefox and chrome, both on android and ubuntu 20.04, full reloads, no luck.

**Comment by Benjaminimal** [comment]
I just tried to register a device and can confirm this.

### Environment:

- OS: debian buster
- Browser: Mozilla Firefox 78.6.0 & Chromium 83.0.4103.116

**Comment by goldyfruit** [comment]
Certainly due to this incident: https://community.mycroft.ai/t/pairing-is-currently-offline/9934

**Comment by chrisveilleux** [comment]
You are correct @goldyfruit.  This was an issue with a release of the code that updated to Angular 10.  Closing this issue.
