### ISSUE TITLE
Rename this Project

### ISSUE THREAD

**Issue by hammyMarc** [MycroftAI/selene-backend#263]
Guys, the naming conventions for the "product components" is all over the board, depending on who's information you read. In recognition of the fact that this is a community project, I _recommend_ that you simplify the component nomenclature. Call the server stuff (selene) "Server" and call home "Home". The assistant components could be named "Assistant" or simply "MyCroft"

I know that people whom have worked hard on this project will have strong feelings. I recommend those strong feelings be put aside, in favor of simplicity that will help to drive adoption numbers higher. Project take flight on the winds of high adoption.

Cheers,

Marc

**Comment by ChanceNCounter** [comment]
Counterpoint: what's "Home" in this context?

**Comment by hammyMarc** [comment]
Should have included this in the original post. Apology.

https://mycroft.ai/blog/mycroft-personal-server-conversation/

**Comment by ChanceNCounter** [comment]
I'm still confused.

**Comment by hammyMarc** [comment]
The author of the link (above) makes refence to components of the Mycroft architecture that do not appear to correlate to items in this repo. At least, they don't seem to correlate. Thoughts?

**Comment by JarbasAl** [comment]
this repository is not a community project at all

your confusions comes from the personal-backend, you can find that here https://github.com/OpenVoiceOS/OVOS-local-backend

regardless, feels quite odd to ask someone to rename their project...

**Comment by ChanceNCounter** [comment]
The author of the link above was writing in 2018, about a roadmap which didn't exist yet. This repository represents the backend you use to configure your Mycroft devices when you use home.mycroft.ai; the personal backend to which Penrod was referring has existed in a few places, as a community project, and, indeed, is currently ☝️

The component you refer to as the "client," Mycroft-core, is standalone software. OOTB, it's coupled with this, but just for config. Most users will want browser-based config, after all. On paper, you don't *need* a backend at all to configure Mycroft. Remote config just feeds on-device config files.

At any rate, Selene is by no means the "server component" of Mycroft. It's a backend used *by* Mycroft to make built-in stuff more accessible for general users, since smart speakers don't have keyboards.

**Comment by hammyMarc** [comment]
Hmmmm 2018. Regardless of the date of authorship, that information is presented within the domain of mycroft.ai therefore one could assume that the information represents the product. 

My experience, while anecdotal, demonstrates that the product and available product information lacks a cohesion and clarity. This lack of cohesion and clarity will inhibit adoption.

FYI I'm a project backer and put my money where my mouth is... so I'm not taking pot shots from the peanut gallery :)

Hope you guys will consider making some moves toward clear and consistent naming conventions. Have a wonderful weekend.

**Comment by krisgesling** [comment]
Hey, I agree that we can improve our naming of things and I think we want to move away from "Home" altogether as it's a bit too generic. So easy to confuse with the Home screen, website home, etc.

Currently "Home" or "home.mycroft.ai" is what we refer to the backend services used by end-users.

Selene is the software that currently provides those backend services. The previous software was called Tartarus but for end-users it was "the old Home" and "the new Home". 

Whilst you can write a new frontend for the Selene-backend, it's not something that we intend to do. So really the two repo's are tied. Together they are Selene.

The Personal Server and the OVOS Local Backend, are both replacements for home.mycroft.ai as a whole. Neither are intended to be a Selene alternative as they are intentionally about personal usage or single devices, and certainly neither would replace only Selene-backend or Selene-frontend.

Does that clarify the naming?

**Comment by chrisveilleux** [comment]
This repository, along with Selene UI, are the "official" server applications for Mycroft devices.  They replace an application named Tartarus.  The code in this repository can be used to build a personal backend, but it was mainly written to run on Mycroft's servers for users that don't want to go to the trouble of building their own backend.  

Future enhancements to Selene may include more "personal backend friendly" updates, but that is not on the company's roadmap at this time.
