### ISSUE TITLE
geography.region UnicodeEncodeError

### ISSUE THREAD

**Issue by deathbybandaid** [MycroftAI/selene-backend#275]
**Describe the bug**
 admin1CodesASCII.txt possibly has changed and selene-backand cannot correctly import the information.

**To Reproduce**
Follow all steps in README.md until `pipenv run python bootstrap_mycroft_db.py`

**Expected behavior**
Database information should populate normally.

**Log files**
````
Populating geography.country table
Populating geography.region table
Traceback (most recent call last):
  File "bootstrap_mycroft_db.py", line 381, in <module>
    _populate_db()
  File "bootstrap_mycroft_db.py", line 371, in _populate_db
    _populate_region_table(mycroft_db)
  File "bootstrap_mycroft_db.py", line 276, in _populate_region_table
    db.execute_sql(region_insert, insert_args)
  File "bootstrap_mycroft_db.py", line 117, in execute_sql
    _cursor.execute(sql, args)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 9: ordinal not in range(128)
````

**Environment (please complete the following information):**
Proxmox LXC Ubuntu 18.04
8GB ram, 100GB storage, 4 CPUs.

**Additional context**

**Comment by simcop2387** [comment]
This is fixable by setting the client encoding on the database handle to utf8.  I will make a PR to the bootstrap script shortly.
